import { Badge } from './Badge'

const STATUS_MAP = {
  applied: { label: 'Applied', variant: 'default' },
  under_review: { label: 'Under Review', variant: 'info' },
  shortlisted: { label: 'Shortlisted', variant: 'info' },
  interview_scheduled: { label: 'Interview Scheduled', variant: 'warning' },
  interview_completed: { label: 'Interview Completed', variant: 'info' },
  background_verification: { label: 'Background Verification', variant: 'warning' },
  offer_extended: { label: 'Job Offer', variant: 'warning' },
  hired: { label: 'Hired', variant: 'success' },
  rejected: { label: 'Rejected', variant: 'danger' },
  cancelled: { label: 'Cancelled', variant: 'default' },
  pending: { label: 'Pending', variant: 'warning' },
  confirmed: { label: 'Confirmed', variant: 'success' },
  active: { label: 'Active', variant: 'success' },
  closed: { label: 'Closed', variant: 'default' },
  terminated: { label: 'Terminated', variant: 'danger' },
  completed: { label: 'Completed', variant: 'success' },
  accepted: { label: 'Accepted', variant: 'success' },
  declined: { label: 'Declined', variant: 'danger' },
  rescheduled: { label: 'Rescheduled', variant: 'info' },
  verified: { label: 'Verified', variant: 'success' },
  unverified: { label: 'Unverified', variant: 'default' },
  suspended: { label: 'Suspended', variant: 'danger' },
  not_submitted: { label: 'Not Submitted', variant: 'default' },
  pending_review: { label: 'Pending Review', variant: 'warning' },
  accredited: { label: 'Accredited', variant: 'success' },
  draft: { label: 'Draft', variant: 'default' },
  published: { label: 'Published', variant: 'success' },
  filled: { label: 'Filled', variant: 'info' },
  submitted: { label: 'Submitted', variant: 'info' },
  endorsed: { label: 'Endorsed', variant: 'warning' },
  for_release: { label: 'For Release', variant: 'warning' },
  approved: { label: 'Approved', variant: 'success' },
  enrolled: { label: 'Enrolled', variant: 'info' },
  waitlisted: { label: 'Waitlisted', variant: 'warning' },
  attended: { label: 'Attended', variant: 'success' },
  offered: { label: 'Offered', variant: 'warning' },
  withdrawn: { label: 'Withdrawn', variant: 'default' },
  pending_deployment: { label: 'Pending Deployment', variant: 'warning' },
  probationary: { label: 'Probationary', variant: 'info' },
  regular: { label: 'Regular', variant: 'success' },
  contract_ended: { label: 'Contract Ended', variant: 'default' },
  resigned: { label: 'Resigned', variant: 'default' },
  requested: { label: 'Requested', variant: 'warning' },
  ongoing: { label: 'Ongoing', variant: 'info' },
  archived: { label: 'Archived', variant: 'default' },
  upcoming: { label: 'Upcoming', variant: 'info' },
  certificate_issued: { label: 'Certificate Issued', variant: 'success' },
}

export function StatusBadge({ status, label }) {
  const entry = STATUS_MAP[status] || { label: status?.replace(/_/g, ' ') || 'Unknown', variant: 'default' }
  return <Badge variant={entry.variant} className="capitalize">{label || entry.label}</Badge>
}
